// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRoleOrigin } from "./AgentRoleOrigin";
import type { AgentRolePlannerCapabilities } from "./AgentRolePlannerCapabilities";

export type AgentRoleListEntry = { id: string, description: string | null, origin: AgentRoleOrigin, hasLockedRuntimeSettings: boolean, plannerCapabilities: AgentRolePlannerCapabilities | null, };
