// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentRolePlannerCapabilities = { workModes: Array<string>, problemClasses: Array<string>, authorityScopes: Array<string>, participantKinds: Array<string>, requiredCompanions: Array<string>, incompatibleRoles: Array<string>, allowedStances: Array<string>, relativeCost: string | null, relativeToolUse: string | null, supportsMultipleStances: boolean, proposalBearing: boolean, };
