// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaCompositionContract } from "./MemythosArenaCompositionContract";
import type { MemythosArenaCompositionLease } from "./MemythosArenaCompositionLease";
import type { MemythosArenaCompositionLifecycleState } from "./MemythosArenaCompositionLifecycleState";
import type { MemythosArenaCompositionRevision } from "./MemythosArenaCompositionRevision";
import type { MemythosRoom } from "./MemythosRoom";

export type MemythosArenaCompositionSnapshot = { contract: MemythosArenaCompositionContract, compositionVersion: number, lifecycleState: MemythosArenaCompositionLifecycleState, appliedRevision?: MemythosArenaCompositionRevision | null, room: MemythosRoom, leases: Array<MemythosArenaCompositionLease>, plannedTokenBudget?: number | null, eventRefs: Array<string>, };
