// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaResumeExecutionMode = "initial_round" | "retain_decision" | "reassess_affected_positions" | "full_round";
