// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaLifecycleState } from "./MemythosArenaLifecycleState";

export type MemythosArenaParent = { arenaId: string, threadId: string, parentRole: string, stanceProfile: string, authorityScope: Array<string>, lifecycleState: MemythosArenaLifecycleState, };
