// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaMessage = { messageId: string, caseId: string, arenaId: string, roundId: string, fromParentThreadId: string, fromParentRole: string, toParentThreadId: string, toParentRole: string, messageKind: string, humanSummary: string, contextPacketRef: string, artifactRefs: Array<string>, requiresResponse: boolean, responseContract?: string | null, };
