// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaLifecycleState } from "./MemythosArenaLifecycleState";

export type MemythosThreadAttachment = { attachmentId: string, arenaId: string, threadId: string, roleId?: string | null, stanceId?: string | null, objective?: string | null, contractRef?: string | null, lifecycleState: MemythosArenaLifecycleState, };
