// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosRoomActivityLifecycle = { roomState: string, activeTurns: number, completedTurns: number, failedTurns: number, cleanClose: boolean, forceClosed: boolean, };
