// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaResumeDisposition } from "./MemythosArenaResumeDisposition";
import type { MemythosArenaResumeExecutionPlan } from "./MemythosArenaResumeExecutionPlan";

export type MemythosArenaResumeAssessment = { disposition: MemythosArenaResumeDisposition, rationale: string, affectedParticipantIds: Array<string>, citedChangeRefs: Array<string>, affectedDecisionRefs: Array<string>, comparabilityInvalidated: boolean, avoidedFullRound: boolean, resumeExecutionPlan: MemythosArenaResumeExecutionPlan, };
