// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosTokenUsageBreakdown } from "./MemythosTokenUsageBreakdown";

export type MemythosTurnUsageAttribution = { threadId: string, turnId: string, arenaId: string, roundId?: string | null, phase?: string | null, parentRole?: string | null, stanceProfile?: string | null, goalRef?: string | null, activationReason?: string | null, participantId?: string | null, causationId?: string | null, correlationId?: string | null, usage: MemythosTokenUsageBreakdown, costWeightedUsage?: bigint | null, evidenceOutcome: string, eventRef: string, };
