// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaDecisionMethod = "single_expert" | "expert_review" | "ranked_selection" | "competitive_debate" | "betting_round";
