// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaMessageDelivery = { deliveryId: string, messageId: string,
/**
 * Semantic message shown in room timelines. The execution prompt may wrap this
 * with transport context, but that envelope is not conversational content.
 */
humanSummary: string, status: string, senderThreadId: string, receiverThreadId: string, arenaId: string, roundId: string, phase?: string | null, deliveryMechanism: string, receiverTurnId?: string | null, receiverResponseEventRef?: string | null, deliveredAsHumanInstruction: boolean, memoryReplayRequired: boolean, eventRefs: Array<string>, rejectionReason?: string | null, };
