// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaCompositionRevisionActionKind } from "./MemythosArenaCompositionRevisionActionKind";

export type MemythosArenaCompositionRevisionAction = { action: MemythosArenaCompositionRevisionActionKind, participantId: string, threadId?: string | null, reason: string, };
