// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosParentRole } from "./MemythosParentRole";
import type { MemythosParentStance } from "./MemythosParentStance";

export type MemythosParentConfiguration = { threadId: string, roomId: string, arenaId: string, registeredRole: MemythosParentRole, effectiveAgentRole?: string | null, stance: MemythosParentStance, goalRef?: string | null, authorityScope: Array<string>, personality?: string | null, multiAgentMode?: string | null, parentThreadId?: string | null, collaborationMode: string, sessionSource: string, configSources: Array<string>, lifecycleState: string, blockers: Array<string>, };
