// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaCompositionCoordination } from "./MemythosArenaCompositionCoordination";
import type { MemythosArenaCompositionParticipant } from "./MemythosArenaCompositionParticipant";
import type { MemythosArenaCostEnvelope } from "./MemythosArenaCostEnvelope";

export type MemythosArenaCompositionContract = { contractVersion: string, arenaId: string, sharedObjective: string, completionCriteria: Array<string>, participants: Array<MemythosArenaCompositionParticipant>, coordination: MemythosArenaCompositionCoordination, costEnvelope: MemythosArenaCostEnvelope, effortRationale: string, rationale: string, unresolvedRoleGap?: string | null, };
