// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaCheckpointState = "phase_open" | "collecting_mailbox_contributions" | "checkpoint_ready" | "checkpoint_sealed" | "concierge_synthesis" | "next_phase_dispatched" | "material_exception" | "concierge_exception_handling" | "replan" | "aborted";
