// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaAggregateContract } from "./MemythosArenaAggregateContract";
import type { MemythosArenaDeliveryPolicy } from "./MemythosArenaDeliveryPolicy";

export type MemythosArenaMessage = { messageId: string, caseId: string, arenaId: string, roundId: string, fromParentThreadId: string, fromParentRole: string, toParentThreadId: string, toParentRole: string, messageKind: string, humanSummary: string,
/**
 * Prompt delivered to the target parent turn. When absent, human_summary is used.
 * Keeping it separate prevents protocol-only constraints from polluting room dialogue.
 */
executionPrompt?: string | null, contextPacketRef: string, artifactRefs: Array<string>, requiresResponse: boolean, deliveryPolicy?: MemythosArenaDeliveryPolicy | null, aggregateContract?: MemythosArenaAggregateContract | null, responseContract?: string | null, };
