// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaComparableCostEvidence = { evidenceRef: string, tokensUsed: bigint, acceptedResult: boolean, comparabilityRationale: string, };
