// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosLayerKind } from "./MemythosLayerKind";

export type MemythosLayer = { layerId: string, name: string, kind: MemythosLayerKind, parentLayerId?: string | null, objective: string, };
