// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosPromptOrigin } from "./MemythosPromptOrigin";

export type MemythosPromptLineagePart = { origin: MemythosPromptOrigin, summary: string, sourceRef?: string | null, };
