// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosParentPeerResponseKind } from "./MemythosParentPeerResponseKind";
import type { MemythosSemanticAlignment } from "./MemythosSemanticAlignment";

export type MemythosParentPeerResponseObservation = { observationId: string, messageId: string, receiverThreadId: string, receiverTurnId?: string | null, responseEventRef?: string | null, observedResponseKind: MemythosParentPeerResponseKind, rolePreserved: boolean, treatedAsHumanInstruction: boolean, semanticAlignment: MemythosSemanticAlignment, actionableNextStep?: string | null, evidenceRefs: Array<string>, };
