// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosParentContinuityStatus } from "./MemythosParentContinuityStatus";
import type { ThreadGoalStatus } from "./ThreadGoalStatus";

export type MemythosParentThreadContinuity = { arenaId: string, threadId: string, parentRole: string, stanceProfile: string, continuityStatus: MemythosParentContinuityStatus, firstTurnId: string | null, latestTurnId: string | null, observedTurnCount: number, memoryReplayRequired: boolean, goalSnapshotAvailable: boolean, goalSnapshotRef?: string | null, budgetStateRef?: string | null, goalStatus?: ThreadGoalStatus | null, tokenBudget?: bigint | null, tokensUsed?: bigint | null, timeUsedSeconds?: bigint | null, latestTurnCompletedRef?: string | null, tokenUsageRef?: string | null, evidenceRefs: Array<string>, degradedReasons: Array<string>, };
