// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosParentRole } from "./MemythosParentRole";
import type { MemythosParentStance } from "./MemythosParentStance";
import type { MemythosRoomActorKind } from "./MemythosRoomActorKind";

export type MemythosRoomActorRef = { kind: MemythosRoomActorKind, threadId?: string | null, parentKey?: string | null, role?: MemythosParentRole | null, stance?: MemythosParentStance | null, label?: string | null, };
