// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaCompositionLifecycleState = "provisioning" | "active_proposals" | "recomposition_requested" | "applying_revision" | "closing" | "closed" | "blocked_catalog_gap" | "blocked_authority" | "failed_provisioning";
