// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosRoomActorRef } from "./MemythosRoomActorRef";

export type MemythosRoomDialogueEntry = { cursor: string, iteration: bigint, sequence: bigint, roomId: string, arenaId: string, threadId: string, turnId: string, roundId?: string | null, phase?: string | null, kind: string, sender: MemythosRoomActorRef, recipient: MemythosRoomActorRef, text: string, sourceItemRef: string, causalRef: string, };
