// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosMailboxResolutionAuditRecord = { id: bigint, receiverThreadId: string, communicationId: string, commandId: string, resolutionGeneration: bigint, action: string, actor: string, reason: string, preStatus: string, preAttemptCount: bigint, preFailureFingerprint?: string | null, preLastProgressRef?: string | null, preQuarantineReason?: string | null, prePayloadHash: string, resultingStatus: string, replacementCommunicationId?: string | null, createdAtMs: bigint, };
