// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaAggregateState = "open" | "collecting" | "ready_by_expected_sources" | "ready_by_quorum" | "sealed" | "recipient_triggered" | "consumed" | "sealed_incomplete" | "exception_routed";
