// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaCostExhaustionPolicy = "wrap_up_then_replan" | "request_expansion" | "change_method";
