// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosThreadConsolidationSourceRef = { threadId: string, turnRefs: Array<string>, itemsView: string, cursor?: string | null, nextCursor?: string | null, latestAgentMessageRef?: string | null, latestAgentMessageText?: string | null, technicalEvidenceRefs: Array<string>, };
