// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReasoningEffort } from "../ReasoningEffort";

export type MemythosArenaCompositionParticipant = { participantId: string, agentRole: string, stance: string, authorityScope: Array<string>, roleObjective: string, expectedContribution: string, exitCondition: string, effortIntent: string,
/**
 * Native app-server effort applied to every turn for this parent in the arena.
 * The composition planner selects it from the OOTB ReasoningEffort values.
 */
reasoningEffort: ReasoningEffort, tokenBudget?: number | null, };
