// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaKind } from "./MemythosArenaKind";
import type { MemythosArenaLifecycleState } from "./MemythosArenaLifecycleState";

export type MemythosArena = { arenaId: string, layerId: string, name: string, kind: MemythosArenaKind, lifecycleState: MemythosArenaLifecycleState, objective: string, participantIds: Array<string>, };
