// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosRoomActorKind = "app_server" | "human" | "parent_thread" | "room_concierge" | "memythos_runtime" | "subagent" | "tool";
