// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosParentRole } from "./MemythosParentRole";
import type { MemythosParentStance } from "./MemythosParentStance";
import type { MemythosPromptLineagePart } from "./MemythosPromptLineagePart";
import type { MemythosPromptOrigin } from "./MemythosPromptOrigin";

export type MemythosParentSetup = { threadId: string, roomId: string, arenaId: string, role: MemythosParentRole, stance: MemythosParentStance, goalRef?: string | null, setupPrompt: string, promptOrigin: MemythosPromptOrigin, promptLineage: Array<MemythosPromptLineagePart>, };
