// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosPromptOrigin = "human_prompt_injection" | "agent_to_agent_prompt" | "memythos_tool_injection" | "memythos_runtime_setup" | "app_server_codex_agentic" | "app_server_protocol" | "mixed";
