// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosRoomParticipant } from "./MemythosRoomParticipant";

export type MemythosRoom = { roomId: string, caseId: string, layerId: string, arenaId: string, topology: string, participants: Array<MemythosRoomParticipant>, };
