// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaLateArrivalPolicy } from "./MemythosArenaLateArrivalPolicy";

export type MemythosArenaAggregateContract = { aggregateId: string, recipientThreadId: string, expectedSourceThreadIds: Array<string>, quorum: number, phaseId: string, deadlineRef?: string | null, completionCriteriaRef: string, lateArrivalPolicy: MemythosArenaLateArrivalPolicy, };
