// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosRoomSendInputDelivery = { threadId: string, turnId: string, eventRefs: Array<string>, roomId: string, roomMessageRef: string, deliveryRef: string, deliveryMechanism: string, humanInstruction: boolean, messageAuthority: string, };
