// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosRoomActivityParticipant = { parentKey: string, threadId: string, parentRole: string, stanceProfile: string, status: string, goalRef?: string | null, deliveryCount: number, activeTurnCount: number, completedTurnCount: number, failedTurnCount: number, activityEventCount: number, lastActivitySummary?: string | null, };
