// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosRoomActivityItem } from "./MemythosRoomActivityItem";

export type MemythosRoomActivityTurn = { parentKey: string, threadId: string, turnId: string, roundId?: string | null, phase?: string | null, status: string, items: Array<MemythosRoomActivityItem>, };
