// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaCostEnvelopeMode } from "./MemythosArenaCostEnvelopeMode";
import type { MemythosArenaCostExhaustionPolicy } from "./MemythosArenaCostExhaustionPolicy";

export type MemythosArenaCostEnvelope = { mode: MemythosArenaCostEnvelopeMode, rationale: string, baselineRefs: Array<string>, totalTokenBudget?: number | null, coordinationTokenBudget?: number | null, substantiveTokenBudget?: number | null, methodIntegrityFunded: boolean, exhaustionPolicy: MemythosArenaCostExhaustionPolicy, };
