// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosEventChannel } from "./MemythosEventChannel";
import type { MemythosTelemetryRefKind } from "./MemythosTelemetryRefKind";
import type { MemythosTelemetrySource } from "./MemythosTelemetrySource";

export type MemythosTelemetryRef = { telemetryRefId: string, kind: MemythosTelemetryRefKind, source: MemythosTelemetrySource, layerId?: string | null, arenaId?: string | null, threadId?: string | null, nativeEventRef?: string | null, detailRef?: string | null, channel: MemythosEventChannel, summary: string, };
