// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaAggregateState } from "./MemythosArenaAggregateState";
import type { MemythosArenaDeliveryPolicy } from "./MemythosArenaDeliveryPolicy";

export type MemythosRoomSendInputDelivery = { deliveryId: string, threadId: string, turnId?: string | null, roundId: string, eventRefs: Array<string>, roomId: string, roomMessageRef: string, deliveryRef: string, deliveryMechanism: string, humanInstruction: boolean, messageAuthority: string, status: string, deliveryPolicy?: MemythosArenaDeliveryPolicy | null, aggregateState?: MemythosArenaAggregateState | null, };
