// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosArenaResumeContext = { previousDecisionRefs: Array<string>, previousEvidenceRefs: Array<string>, candidateChangeRefs: Array<string>,
/**
 * Decisions that remain authoritative unless cited evidence materially invalidates them.
 */
protectedDecisions: Array<string>,
/**
 * Prior hypotheses, weights, or interpretations that new evidence may revise.
 */
revisableSettlement: Array<string>,
/**
 * Downstream implementation questions that remain open without reopening business decisions.
 */
openImplementationScope: Array<string>, };
