// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosPromptLineagePart } from "./MemythosPromptLineagePart";
import type { MemythosPromptOrigin } from "./MemythosPromptOrigin";
import type { MemythosRoomActorRef } from "./MemythosRoomActorRef";

export type MemythosRoomActivityEvent = { cursor: string, iteration: bigint, sequence: bigint, roomId: string, arenaId: string, threadId: string, turnId?: string | null, roundId?: string | null, phase?: string | null, participantRole: string, channel: string, eventKind: string, status: string, sender: MemythosRoomActorRef, recipient: MemythosRoomActorRef, authority: string, promptOrigin: MemythosPromptOrigin, promptLineage: Array<MemythosPromptLineagePart>, summary: string, sourceRef?: string | null, };
