// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaDecisionMethod } from "./MemythosArenaDecisionMethod";
import type { MemythosArenaRoundPolicy } from "./MemythosArenaRoundPolicy";

export type MemythosArenaCompositionCoordination = { coordinatorParticipantId?: string | null, conciergeParticipantId?: string | null, judgeParticipantId?: string | null, decisionMethod: MemythosArenaDecisionMethod, roundPolicy?: MemythosArenaRoundPolicy | null, };
