// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosRoomActivityItem = { itemId?: string | null, itemType?: string | null, kind: string, status: string, summary: string, text?: string | null, humanHighlight?: string | null, technicalSummary?: string | null, artifactRef?: string | null, eventRef: string, refs: Array<string>, };
