// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaCompositionRevisionAction } from "./MemythosArenaCompositionRevisionAction";

export type MemythosArenaCompositionRevision = { revisionId: string, previousVersion: number, nextVersion: number, previousContractRef: string, trigger: string, rationale: string, actions: Array<MemythosArenaCompositionRevisionAction>, };
