// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosMailboxQuarantineRecord = { receiverThreadId: string, communicationId: string, sourceCallId?: string | null, payloadHash: string, status: string, attemptCount: bigint, failureFingerprint?: string | null, lastProgressRef?: string | null, quarantineReason?: string | null, createdAtMs: bigint, updatedAtMs: bigint, };
