// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosTokenUsageBreakdown } from "./MemythosTokenUsageBreakdown";
import type { MemythosTurnUsageAttribution } from "./MemythosTurnUsageAttribution";

export type MemythosRoomActivityUsage = { tokenUsageEvents: number, refs: Array<string>, total: MemythosTokenUsageBreakdown, turns: Array<MemythosTurnUsageAttribution>, costWeightedUsage?: bigint | null, };
