// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemythosArenaResumeExecutionMode } from "./MemythosArenaResumeExecutionMode";

export type MemythosArenaResumeExecutionPlan = { mode: MemythosArenaResumeExecutionMode, affectedParticipantIds: Array<string>, sourceRoundId?: string | null, affectedDecisionRefs: Array<string>, citedChangeRefs: Array<string>, };
