// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MemythosParentStance = "coordination" | "routing" | "synthesis" | "escalation_control" | "end_to_end_integrity" | "business_fitness" | "customer_flow" | "implementation_pid" | "reality_fit" | "salesforce_delivery" | "growth" | "risk";
